language: python
python:
  - "3.3"

install:
  - "pip install -e ."
  - "pip install pyflakes"
  - "pip install pep8"

script:
  - python setup.py test;
  - pep8 werkzeug_dispatch
  - pyflakes werkzeug_dispatch
