language: python
sudo: false
python:
  - "3.3"
  - "3.4"

install:
  - "pip install -e ."
  - "pip install coveralls"
  - "pip install pyflakes"
  - "pip install pep8"

script:
  - "coverage run --source=jsonconfigparser setup.py test"
  - "pep8 ."
  - "pyflakes ."

after_success:
  - "coveralls"

deploy:
  provider: pypi
  user: "bwhmather-travis"
  password:
    secure: "gBVxW0q1r3OcmSfJU5m4hIbuWxhrxlJKBKhbnhCRZQrskUUbDKzJyS++Xg2EL51t0ZWpIJDFdTVJPL7uWcOJiuDulE8/cD8dnUVf/FKc4mLyAHX5FV3zyzki9iWZLmxoxTP+0XZthTK1kuU/VzNn39LXRqfOvHLllA9KtLb5t5Y="
  on:
    branch: "master"
